apiVersion: v1
kind: Pod
metadata:
  name: static-web
  labels:
    role: myrole
spec:
  containers:
    - name: web
      image: nginx
      ports:
        - name: web
          ports:
            - containerPort: 8080
            - containerPort: 50000
          protocol: TCP
